/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCatchesNewRouteImport } from './routes/_authenticated/catches.new'
import { Route as AuthenticatedOffersIndexRouteImport } from './routes/_authenticated/offers.index'
import { Route as AuthenticatedOffersOfferIdRouteImport } from './routes/_authenticated/offers.$offerId'
import { Route as AuthenticatedCatchesCatchIdIndexRouteImport } from './routes/_authenticated/catches.$catchId.index'
import { Route as AuthenticatedCatchesCatchIdEditRouteImport } from './routes/_authenticated/catches.$catchId.edit'
import { Route as ApiPublicInstagramCallbackRouteImport } from './routes/api/public/instagram/callback'
import { Route as ApiPublicWebhooksResendRouteImport } from './routes/api/public/webhooks/resend'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatchesNewRoute = AuthenticatedCatchesNewRouteImport.update({
  id: '/catches/new',
  path: '/catches/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersIndexRoute =
  AuthenticatedOffersIndexRouteImport.update({
    id: '/offers/',
    path: '/offers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersOfferIdRoute =
  AuthenticatedOffersOfferIdRouteImport.update({
    id: '/offers/$offerId',
    path: '/offers/$offerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatchesCatchIdIndexRoute =
  AuthenticatedCatchesCatchIdIndexRouteImport.update({
    id: '/catches/$catchId/',
    path: '/catches/$catchId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatchesCatchIdEditRoute =
  AuthenticatedCatchesCatchIdEditRouteImport.update({
    id: '/catches/$catchId/edit',
    path: '/catches/$catchId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicInstagramCallbackRoute =
  ApiPublicInstagramCallbackRouteImport.update({
    id: '/api/public/instagram/callback',
    path: '/api/public/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksResendRoute = ApiPublicWebhooksResendRouteImport.update({
  id: '/api/public/webhooks/resend',
  path: '/api/public/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/catches/new': typeof AuthenticatedCatchesNewRoute
  '/offers/$offerId': typeof AuthenticatedOffersOfferIdRoute
  '/offers/': typeof AuthenticatedOffersIndexRoute
  '/catches/$catchId/edit': typeof AuthenticatedCatchesCatchIdEditRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/catches/$catchId/': typeof AuthenticatedCatchesCatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/catches/new': typeof AuthenticatedCatchesNewRoute
  '/offers/$offerId': typeof AuthenticatedOffersOfferIdRoute
  '/offers': typeof AuthenticatedOffersIndexRoute
  '/catches/$catchId/edit': typeof AuthenticatedCatchesCatchIdEditRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/catches/$catchId': typeof AuthenticatedCatchesCatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/catches/new': typeof AuthenticatedCatchesNewRoute
  '/_authenticated/offers/$offerId': typeof AuthenticatedOffersOfferIdRoute
  '/_authenticated/offers/': typeof AuthenticatedOffersIndexRoute
  '/_authenticated/catches/$catchId/edit': typeof AuthenticatedCatchesCatchIdEditRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/_authenticated/catches/$catchId/': typeof AuthenticatedCatchesCatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/settings'
    | '/catches/new'
    | '/offers/$offerId'
    | '/offers/'
    | '/catches/$catchId/edit'
    | '/api/public/instagram/callback'
    | '/api/public/webhooks/resend'
    | '/catches/$catchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/history'
    | '/settings'
    | '/'
    | '/catches/new'
    | '/offers/$offerId'
    | '/offers'
    | '/catches/$catchId/edit'
    | '/api/public/instagram/callback'
    | '/api/public/webhooks/resend'
    | '/catches/$catchId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/history'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/catches/new'
    | '/_authenticated/offers/$offerId'
    | '/_authenticated/offers/'
    | '/_authenticated/catches/$catchId/edit'
    | '/api/public/instagram/callback'
    | '/api/public/webhooks/resend'
    | '/_authenticated/catches/$catchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicInstagramCallbackRoute: typeof ApiPublicInstagramCallbackRoute
  ApiPublicWebhooksResendRoute: typeof ApiPublicWebhooksResendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catches/new': {
      id: '/_authenticated/catches/new'
      path: '/catches/new'
      fullPath: '/catches/new'
      preLoaderRoute: typeof AuthenticatedCatchesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/': {
      id: '/_authenticated/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof AuthenticatedOffersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/$offerId': {
      id: '/_authenticated/offers/$offerId'
      path: '/offers/$offerId'
      fullPath: '/offers/$offerId'
      preLoaderRoute: typeof AuthenticatedOffersOfferIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catches/$catchId/': {
      id: '/_authenticated/catches/$catchId/'
      path: '/catches/$catchId'
      fullPath: '/catches/$catchId/'
      preLoaderRoute: typeof AuthenticatedCatchesCatchIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catches/$catchId/edit': {
      id: '/_authenticated/catches/$catchId/edit'
      path: '/catches/$catchId/edit'
      fullPath: '/catches/$catchId/edit'
      preLoaderRoute: typeof AuthenticatedCatchesCatchIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/instagram/callback': {
      id: '/api/public/instagram/callback'
      path: '/api/public/instagram/callback'
      fullPath: '/api/public/instagram/callback'
      preLoaderRoute: typeof ApiPublicInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/resend': {
      id: '/api/public/webhooks/resend'
      path: '/api/public/webhooks/resend'
      fullPath: '/api/public/webhooks/resend'
      preLoaderRoute: typeof ApiPublicWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCatchesNewRoute: typeof AuthenticatedCatchesNewRoute
  AuthenticatedOffersOfferIdRoute: typeof AuthenticatedOffersOfferIdRoute
  AuthenticatedOffersIndexRoute: typeof AuthenticatedOffersIndexRoute
  AuthenticatedCatchesCatchIdEditRoute: typeof AuthenticatedCatchesCatchIdEditRoute
  AuthenticatedCatchesCatchIdIndexRoute: typeof AuthenticatedCatchesCatchIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCatchesNewRoute: AuthenticatedCatchesNewRoute,
  AuthenticatedOffersOfferIdRoute: AuthenticatedOffersOfferIdRoute,
  AuthenticatedOffersIndexRoute: AuthenticatedOffersIndexRoute,
  AuthenticatedCatchesCatchIdEditRoute: AuthenticatedCatchesCatchIdEditRoute,
  AuthenticatedCatchesCatchIdIndexRoute: AuthenticatedCatchesCatchIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicInstagramCallbackRoute: ApiPublicInstagramCallbackRoute,
  ApiPublicWebhooksResendRoute: ApiPublicWebhooksResendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
